name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: force node version to match home version
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: dist
          build: npm run build
          start: npm start
          
#   cypress-run:
#     runs-on: windows-latest
#     steps:
#       - name: Checkout SUT
#         uses: actions/checkout@v1

#       - name: Run backend
#         uses: actions/setup-node@v1
#         with:
#           node-version: 14.17.4
# #           run: npm run start

#       - name: Cypress run
#         uses: cypress-io/github-action@v1
#         with:
#           record: true
#           start: npm run serve --prefix dist
#           wait-on: http://localhost:8080
#         env:
#           # pass the Dashboard record key as an environment variable
#           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
