name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Installing project dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start

      - name: force node version to match home version
        uses: actions/setup-node@master
        with:
          node-version: '14.17.4'

      - name: Installing project dependencies
        run: npm install

      - name: Run the thing using the debugging server
        run: npm run serve &

      - name: test it
        run: npx cypress run  --record --key  ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --spec "**/ci-gateway/**"
