name: Cypress Tests

on:
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
        - name: get my stuff
          uses: actions/checkout@v2 
          
        - name: get node
          uses: actions/setup-node@master
          
        - name: install it all and make a localhost
        - run: npm install
        - run: npm run serve
        
        - name: Cypress run
          uses: cypress-io/github-action@v2
 
