name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: force node version to match home version
        uses: actions/setup-node@master
        with:
          node-version: '14.17.4'

      - name: Installing project dependencies
        run: npm install

      - name: Run the thing using the debuggeing server
        run: npm run serve &

      - name: test it
        #        run: npx cypress run  --record --key  ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --spec "**/ci-gateway/**"
        run: npx cypress run  --browser chrome --spec "**/ci-gateway/**"

  build_and_deploy:
    needs: [ cypress-run ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'npm ci && npm run build'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DAILY_DILETTANTE }}'
          channelId: live
          projectId: daily-dilettante
