name: Cypress Tests

on:
  push:
  workflow_dispatch:

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get SUT
        uses: actions/checkout@master
        
      - name: get node
        uses: actions/setup-node@master
        
      - name: Installing project dependencies
        run: npm install
        
      - name: Building the project
        run: npm run build
