name: CI/CD gateway

on:
  push:
  workflow_dispatch:

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: get SUT
        uses: actions/checkout@master

      - name: get node
        uses: actions/setup-node@master

      - name: Installing project dependencies
        run: npm install

      - name: Building the project
        run: npm run build
